# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from django.utils.translation import gettext_lazy as _

help_texts = {
    'lino_noi.lib.noi.migrate.Migrator' : _("""The standard migrator for noi."""),
    'lino_noi.lib.noi.migrate.Migrator.migrate_from_1_0_1' : _("""Move Deployment and Milestone from 'tickets' to new plugin
'deploy'."""),
    'lino_noi.lib.noi.user_types.Customer' : _("""A Customer is somebody who uses our software and may report
tickets, but won't work on them. Able to comment and view tickets on sites
where they are contact people. Unable to see any client data other than orgs
where they are a contact person and themselves."""),
    'lino_noi.lib.noi.user_types.Contributor' : _("""A Contributor is somebody who works on and see tickets of sites they are team members of."""),
    'lino_noi.lib.noi.user_types.Developer' : _("""A Developer is a trusted user who has signed an NDA, has access to client contacts.
Is able to make service reports as well as manage tickets."""),
    'lino_noi.lib.noi.user_types.SiteAdmin' : _("""Can do everything."""),
    'lino_noi.lib.tickets.Ticket' : _("""The Django model used to represent a ticket in Noi. Adds some fields and
methods."""),
    'lino_noi.lib.tickets.Ticket.assigned_to' : _("""The user who is working on this ticket."""),
    'lino_noi.lib.tickets.Ticket.site' : _("""The site this ticket belongs to.
You can select only sites you are subscribed to."""),
    'lino_noi.lib.noi.UserTypes.user' : _("""An alias for customer."""),
    'lino_noi.lib.noi.UserTypes.customer' : _("""Somebody who uses some part of the software being developed by
the team. This is usually the contact person of a customer."""),
    'lino_noi.lib.noi.UserTypes.contributor' : _("""Can submit tickets, work on them and discuss with other team members.  Does
not see confidential data nor the tickets of other teams."""),
    'lino_noi.lib.noi.UserTypes.developer' : _("""A trusted contributor who can do almost everything except managing other
users."""),
    'lino_noi.lib.noi.UserTypes.admin' : _("""Can see everything including create new end users, change
their passwords, assign them to teams."""),
}
